### PR TITLE
HW3 1 attempt

### PR DESCRIPTION
**Pull request by slendersold**
accept pls

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi Georgii, nice work!

Several comments:

You had the following description in the task
```
# check if smth passed to upper_border and if it is valid speed value
# if True, increase the speed gradually iterating over your increaser until upper_border is met
# print a message at each speed increase
# else increase the speed once
```
I guess, currently your code does not support the latter option - to increase speed just once by some default value calling just `accelerate()`

Another description from the task states the following:
```
    def parking(self):
        # gets car off the road (use state and class variable)
        # check: should not be able to move the car off the road if it's not there
```
I think, you do not check for car state in your `parking` method. Nothing wrong happens here but some message would be beneficial (like 'Parking the car..." if `state==ON_ROAD` or "The car is already parked" in case it's `state==PARKING` )

And the last comment: in your iterator there is no `StopIteration` condition, which is one of the important features for object to be considered as an Iterator. Please think, how to incorporate it in your `__next__ `methods, when the max/min values are reached.

**Comment by rinnifox** [comment]
Ok, good!

Now working with your updated Car class, I noticed another issue. 
You create iterators in Car's `__init__` and pass there the `current_speed` value. For increasing this works fine, but for decreasing the following situation happens: when creating a car with speed=0, you initialize the decreasing iterator with the `current_speed=0`, which means that according to your `StopIteration` condition, one cannot pass 0 once again there. So it becomes impossible to properly call `break()` (and `parking()` as well) after accelerating from 0 speed. Check this please :)

**Comment by slendersold** [comment]
@rinnifox  I made a try

**Comment by rinnifox** [comment]
Good! You can merge this PR into main.

**Pull request merged**
